### ISSUE TITLE
Macos windchill shell output encoding problem

### ISSUE THREAD

**Issue by b-m-r** [d-wojciechowski/plm-companion#27]
The windchill shell output on macos has some problems with undefined characters.

**To Reproduce**
1. xconfmanager -d wt.home
2. run the command

**Screenshots**
![Screenshot 2020-05-26 at 15 28 41](https://user-images.githubusercontent.com/65961074/82908186-e7586800-9f67-11ea-94f1-b26a8c6e00cc.png)

**Desktop (please complete the following information):**
 - OS: [macos 10.15.4]
 - Intellij: 2020.1

PS: Otherwise I like the plugin a lot! thanks for your effort

**Comment by d-wojciechowski** [comment]
It seems it is a problem with encoding difference between Windows and MacOS. In near future I will try to mitigate this issue. Thanks for issue report.

**Comment by d-wojciechowski** [comment]
Unfortunately new Windows 10 20H1 broke virtualization on my computer and I am not able to run MacOS or Linux VM at all. Need to wait for fix by MS.

Fix will be postponed for now on 0.9.0, with possibility to postpone even further.

**Comment by d-wojciechowski** [comment]
After a long time, Virtualization on my PC started to work, it seems that was a problem with a Unicode zero byte character `\u0000`. Implemented some workaround for it.
Fix will be in the next release 0.9.0

![image](https://user-images.githubusercontent.com/18571662/87242791-4ac32a00-c430-11ea-8bee-6acc23cdf2e3.png)
