### ISSUE TITLE
loosing custom opened logs after IDE restart

### ISSUE THREAD

**Issue by b-m-r** [d-wojciechowski/plm-companion#51]
When opening a new custom log, the tab is missing after IDE restart.

**To Reproduce**
1. Open new log with the plus sign
2. Close IDE
3. Tab is missing

**Expected behavior**
Custom tab will be opened again 

**Version**
PLM Companion 1.0.0

**Comment by d-wojciechowski** [comment]
@b-m-r  I propose the following solution:
- Tab will be persisted, without any data, just metadata about chosen file.
- To resume tailing, "play" button needs to be clicked.
- Default behavior would be still to not persist "custom logs", this may be changed in the settings window.

Regarding, when that would be implemented.... we will see, right now I stopped the implementation. But stay tuned 😄
